spring:
  datasource:
    master:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://x.x.x.x:3316/db
      username: root
      password: xxx
    slave:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://x.x.x.x:3326/db
      username: root
      password: xxx

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
