spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/sharding_db
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update