spring:
  shardingsphere:
    datasource:
      names: master, slave

      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://x.x.x.x:3316/db
        username: root
        password: xxx

      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://x.x.x.x:3326/db
        username: root
        password: xxx

    sharding:
      master-slave-rules:
        ds0:
          master-data-source-name: master
          slave-data-source-name: slave

          load-balance-algorithm-type: round_robin
    props:
      sql:
        show: true

